const products = [
    {
        id: 1,
        category: "breads",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 44.5,
        skidka: 50,
        rating: 2,
        discount: 2,
        image: "images/image.png",
    },
    {
        id: 2,
        category: "milks",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 49.39,
        skidka: 30,
        rating: 3,
        image: "images/imagee2.png",
    },
    {
        id: 3,
        category: "meats",
        description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/imagee3.png",
    },
    {
        id: 4,
        category: "candies",
        description: "Конфеты очень вкусный и приятный десер Тоскант Сальчичон",
        price: 30,
        skidka: 20,
        rating: 4,
        discount: 4,
        image: "images/imagee2.png",
    },
    {
        id: 5,
        category: "sweets",
        description: "Конфеты готовятся из муки и различных фруктов, очень",
        price: 50,
        skidka: 30,
        rating: 5,
        discount: 4,
        image: "images/img2.png",
    },
    {
        id: 6,
        category: "drinks",
        description: "безалкогольные и газированные напитки пьют в жаркие",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/img5.png",
    },
    {
        id: 7,
        category: "coffees",
        description: "приятный, ароматный напиток, который заставляет вас ",
        price: 70.2,
        skidka: 30,
        rating: 4,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 8,
        category: "fruits",
        description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
        price: 49.7,
        skidka: 50,
        rating: 5,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 9,
        category: "breads",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 44.5,
        skidka: 50,
        rating: 2,
        discount: 2,
        image: "images/image.png",
    },
    {
        id: 10,
        category: "milks",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 49.39,
        skidka: 30,
        rating: 3,
        image: "images/imagee2.png",
    },
    {
        id: 11,
        category: "meats",
        description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/imagee3.png",
    },
    {
        id: 12,
        category: "candies",
        description: "Конфеты очень вкусный и приятный десер Тоскант Сальчичон",
        price: 30,
        skidka: 20,
        rating: 4,
        discount: 4,
        image: "images/imagee2.png",
    },
    {
        id: 13,
        category: "sweets",
        description: "Конфеты готовятся из муки и различных фруктов, очень",
        price: 50,
        skidka: 30,
        rating: 5,
        discount: 4,
        image: "images/img2.png",
    },
    {
        id: 14,
        category: "drinks",
        description: "безалкогольные и газированные напитки пьют в жаркие",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/img5.png",
    },
    {
        id: 15,
        category: "coffees",
        description: "приятный, ароматный напиток, который заставляет вас ",
        price: 70.2,
        skidka: 30,
        rating: 4,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 16,
        category: "fruits",
        description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
        price: 49.7,
        skidka: 50,
        rating: 5,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 17,
        category: "breads",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 44.5,
        skidka: 50,
        rating: 2,
        discount: 2,
        image: "images/image.png",
    },
    {
        id: 18,
        category: "milks",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 49.39,
        skidka: 30,
        rating: 3,
        image: "images/imagee2.png",
    },
    {
        id: 19,
        category: "meats",
        description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/imagee3.png",
    },
    {
        id: 20,
        category: "candies",
        description: "Конфеты очень вкусный и приятный десер Тоскант Сальчичон",
        price: 30,
        skidka: 20,
        rating: 4,
        discount: 4,
        image: "images/imagee2.png",
    },
    {
        id: 21,
        category: "sweets",
        description: "Конфеты готовятся из муки и различных фруктов, очень",
        price: 50,
        skidka: 30,
        rating: 5,
        discount: 4,
        image: "images/img2.png",
    },
    {
        id: 22,
        category: "drinks",
        description: "безалкогольные и газированные напитки пьют в жаркие",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/img5.png",
    },
    {
        id: 23,
        category: "coffees",
        description: "приятный, ароматный напиток, который заставляет вас ",
        price: 70.2,
        skidka: 30,
        rating: 4,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 24,
        category: "fruits",
        description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
        price: 49.7,
        skidka: 50,
        rating: 5,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 25,
        category: "breads",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 44.5,
        skidka: 50,
        rating: 2,
        discount: 2,
        image: "images/image.png",
    },
    {
        id: 26,
        category: "milks",
        description: "Молоко ПРОСТОКВАШИНО паст. питьевое цельное отборное...",
        price: 49.39,
        skidka: 30,
        rating: 3,
        image: "images/imagee2.png",
    },
    {
        id: 27,
        category: "meats",
        description: "Колбаса сырокопченая МЯСНАЯ ИСТОРИЯ Сальчичон и Тоскан...",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/imagee3.png",
    },
    {
        id: 28,
        category: "candies",
        description: "Конфеты очень вкусный и приятный десер Тоскант Сальчичон",
        price: 30,
        skidka: 20,
        rating: 4,
        discount: 4,
        image: "images/imagee2.png",
    },
    {
        id: 29,
        category: "sweets",
        description: "Конфеты готовятся из муки и различных фруктов, очень",
        price: 50,
        skidka: 30,
        rating: 5,
        discount: 4,
        image: "images/img2.png",
    },
    {
        id: 30,
        category: "drinks",
        description: "безалкогольные и газированные напитки пьют в жаркие",
        price: 44.5,
        skidka: 10,
        rating: 5,
        discount: 4,
        image: "images/img5.png",
    },
    {
        id: 31,
        category: "coffees",
        description: "приятный, ароматный напиток, который заставляет вас ",
        price: 70.2,
        skidka: 30,
        rating: 4,
        discount: 4,
        image: "images/img7.png",
    },
    {
        id: 32,
        category: "fruits",
        description: "плоды сладкие, горькие, кислые, богаты витаминами, полезны",
        price: 49.7,
        skidka: 50,
        rating: 5,
        discount: 4,
        image: "images/img7.png",
    },
];
